apiVersion: v1
kind: Service
metadata:
  name: movie-service
spec:
  selector:
    app: movie-service
  ports:
    - port: {{ .Values.movie_service.service.port }}
      targetPort: {{ .Values.movie_service.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: cast-service
spec:
  selector:
    app: cast-service
  ports:
    - port: {{ .Values.cast_service.service.port }}
      targetPort: {{ .Values.cast_service.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
    - port: {{ .Values.nginx_service.service.port }}
      targetPort: {{ .Values.nginx_service.service.port }}
